### ISSUE TITLE
Henshin files in an Xtext project break compilation

### ISSUE THREAD

**Issue by szschaler** [eclipse-henshin/henshin#1]
Including a `.henshin` file in an Xtext project (anything that uses an Xtext builder, so including Xtend projects etc) currently breaks the build with a weird error message just referring to `javax.inject.Provider`. This is because there is a dependency to that class in the Xtext adapters included in Henshin and the class is no longer included with Java by default.

The patch below will fix the issue. I don't have write access to the project -- could someone integrate this for me, please?

```patch
diff --git "a/plugins/adapters/org.eclipse.emf.henshin.adapters.xtext/src/org/eclipse/emf/henshin/adapters/xtext/NamingHelper.xtend" "b/plugins/adapters/org.eclipse.emf.henshin.adapters.xtext/src/org/eclipse/emf/henshin/adapters/xtext/NamingHelper.xtend"
index 48bf6422..07e74422 100644
--- "a/plugins/adapters/org.eclipse.emf.henshin.adapters.xtext/src/org/eclipse/emf/henshin/adapters/xtext/NamingHelper.xtend"
+++ "b/plugins/adapters/org.eclipse.emf.henshin.adapters.xtext/src/org/eclipse/emf/henshin/adapters/xtext/NamingHelper.xtend"
@@ -1,6 +1,6 @@
 package org.eclipse.emf.henshin.adapters.xtext
 
-import javax.inject.Provider
+import com.google.inject.Provider
 import org.eclipse.emf.ecore.EObject
 import org.eclipse.emf.henshin.model.Attribute
 import org.eclipse.emf.henshin.model.Edge
```

Note that `com.google.inject` is already part of the plugin dependencies, so shouldn't cause any extra issues.

**Comment by dstrueber** [comment]
Thanks for this issue, Steffen - just today I sat down to see what has to be done to adapt Henshin to this new GitHub setup, and this was the perfect first issue. Integrating it into the repo was as easy as expected, but re-launching the build turns out to be tricky... I hope I have some positive news soon.

**Comment by szschaler** [comment]
Hah, I was wondering about the setup :-) Glad I found the correct repo...

**Comment by szschaler** [comment]
BTW, I was interested to see you push directly to `master`...

**Comment by dstrueber** [comment]
It looks like the build has worked out [1] (I guess we should migrate the build engineering to GitHub actions at some point).
Feel free to try out by installing from the nightly build update site [2].

[1] https://ci.eclipse.org/henshin/job/cbi_henshin_nightly/1221/
[2] https://download.eclipse.org/modeling/emft/henshin/updates/nightly/

**Comment by szschaler** [comment]
Thanks. I can confirm that the nightly build now works for me. Many thanks!

**Comment by dstrueber** [comment]
Glad to hear - thanks again for contributing the fix!
